
=head1 NAME

ansel-cltest - check if there is a usable OpenCL environment for ansel to use

=head1 SYNOPSIS

    ansel-cltest

=head1 DESCRIPTION

B<ansel> is a digital photography workflow application for B<Linux>, B<Mac OS X> and several other B<Unices>.
It's described further in L<ansel(1)|ansel(1)>.

B<ansel-cltest> checks if there is a usable OpenCL environment on your system that ansel can use.
It emits some debug output that is equivalent to calling B<ansel -d opencl> and then terminates.

=head1 SEE ALSO

L<ansel(1)|ansel(1)>

=head1 AUTHORS

The principal developer of ansel is Johannes Hanika.
The (hopefully) complete list of contributors to the project is:

DREGGNAUTHORS -- don't translate this line!

This man page was written by Ulrich Pegelow E<lt>ulrich.pegelow@tongareva.deE<gt> as part of the usermanual.
It was turned into a man page by Tobias Ellinghaus E<lt>me@houz.orgE<gt>.


=head1 COPYRIGHT AND LICENSE

B<Copyright (C)> 2009-2017 by Authors.

B<ansel> is free software; you can redistribute it and/or modify it
under the terms of the GPL v3 or (at your option) any later version.

=for comment
$Date: 2017-01-20$
$Release: 2.3$
